export interface DummyActivityEvent {
  id: string;
  type: string;
  title: string;
  description: string;
  actor: string;
  timestamp: string;
  metadata?: Record<string, unknown>;
}

export const dummyActivities: DummyActivityEvent[] = [
  {
    id: 'act-1',
    type: 'score_change',
    title: 'Readiness score updated',
    description: 'NeuralPay score increased from 79 to 82',
    actor: 'System',
    timestamp: '2025-02-10T16:00:00Z',
    metadata: { startup_id: 'startup-neuralpay', previous_score: 79, new_score: 82 },
  },
  {
    id: 'act-2',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'NeuralPay Pitch Deck Q1 2025.pdf was uploaded',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T14:30:00Z',
    metadata: { document_id: 'doc-1', category: 'pitch_deck' },
  },
  {
    id: 'act-3',
    type: 'task_completed',
    title: 'Task completed',
    description: '"Add competitive analysis slide" marked as done',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T13:45:00Z',
    metadata: { task_id: 't-2', task_group_id: 'tg-storytelling' },
  },
  {
    id: 'act-4',
    type: 'match_viewed',
    title: 'Match viewed',
    description: 'General Catalyst match (89 score) was viewed',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T12:20:00Z',
    metadata: { match_id: 'match-1', investor: 'General Catalyst' },
  },
  {
    id: 'act-5',
    type: 'chat_message',
    title: 'Chat message sent',
    description: 'New message in "Pitch deck feedback" thread',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T10:15:00Z',
    metadata: { thread_id: 'thread-1' },
  },
  {
    id: 'act-6',
    type: 'task_status_changed',
    title: 'Task status updated',
    description: '"Add unit economics breakdown" set to in progress',
    actor: 'Marcus Webb',
    timestamp: '2025-02-09T16:30:00Z',
    metadata: { task_id: 't-31' },
  },
  {
    id: 'act-7',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'Data Room - Complete.zip was uploaded',
    actor: 'Sarah Chen',
    timestamp: '2025-02-09T08:45:00Z',
    metadata: { document_id: 'doc-7', category: 'data_room' },
  },
  {
    id: 'act-8',
    type: 'match_saved',
    title: 'Match saved',
    description: 'Andreessen Horowitz match saved to shortlist',
    actor: 'Sarah Chen',
    timestamp: '2025-02-09T11:00:00Z',
    metadata: { match_id: 'match-2' },
  },
  {
    id: 'act-9',
    type: 'assessment_run',
    title: 'Assessment completed',
    description: 'Run #5 completed for NeuralPay - score 82',
    actor: 'System',
    timestamp: '2025-02-10T16:00:00Z',
    metadata: { run_id: 'ar-5', startup_id: 'startup-neuralpay' },
  },
  {
    id: 'act-10',
    type: 'profile_update',
    title: 'Profile updated',
    description: 'Founder bios and photos were updated',
    actor: 'Sarah Chen',
    timestamp: '2025-02-08T15:20:00Z',
    metadata: { startup_id: 'startup-neuralpay' },
  },
  {
    id: 'act-11',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'NeuralPay Pitch Deck Q1 2025.pdf was uploaded',
    actor: 'Sarah Chen',
    timestamp: '2025-02-08T10:30:00Z',
    metadata: { document_id: 'doc-1' },
  },
  {
    id: 'act-12',
    type: 'task_completed',
    title: 'Task completed',
    description: '"Upload pitch deck" marked as done',
    actor: 'Sarah Chen',
    timestamp: '2025-02-08T10:35:00Z',
    metadata: { task_id: 't-1' },
  },
  {
    id: 'act-13',
    type: 'match_contacted',
    title: 'Investor contacted',
    description: 'Andreessen Horowitz marked as contacted',
    actor: 'Sarah Chen',
    timestamp: '2025-02-09T14:00:00Z',
    metadata: { match_id: 'match-2' },
  },
  {
    id: 'act-14',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'NeuralPay Financial Model v3.xlsx was uploaded',
    actor: 'Sarah Chen',
    timestamp: '2025-02-07T14:20:00Z',
    metadata: { document_id: 'doc-2' },
  },
  {
    id: 'act-15',
    type: 'task_completed',
    title: 'Task completed',
    description: '"Upload financial model" marked as done',
    actor: 'Sarah Chen',
    timestamp: '2025-02-07T14:25:00Z',
    metadata: { task_id: 't-30' },
  },
  {
    id: 'act-16',
    type: 'score_change',
    title: 'Readiness score updated',
    description: 'NeuralPay score increased from 75 to 79',
    actor: 'System',
    timestamp: '2025-02-05T11:45:00Z',
    metadata: { startup_id: 'startup-neuralpay', previous_score: 75, new_score: 79 },
  },
  {
    id: 'act-17',
    type: 'match_viewed',
    title: 'Match viewed',
    description: 'Sequoia Capital match (86 score) was viewed',
    actor: 'Sarah Chen',
    timestamp: '2025-02-04T09:30:00Z',
    metadata: { match_id: 'match-19' },
  },
  {
    id: 'act-18',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'Product Roadmap 2025.pdf was uploaded',
    actor: 'Marcus Webb',
    timestamp: '2025-02-01T13:30:00Z',
    metadata: { document_id: 'doc-8' },
  },
  {
    id: 'act-19',
    type: 'task_completed',
    title: 'Task completed',
    description: '"Complete team bios" marked as done',
    actor: 'Sarah Chen',
    timestamp: '2025-01-28T11:00:00Z',
    metadata: { task_id: 't-9' },
  },
  {
    id: 'act-20',
    type: 'task_completed',
    title: 'Task completed',
    description: '"Add founder photos" marked as done',
    actor: 'Sarah Chen',
    timestamp: '2025-01-28T11:15:00Z',
    metadata: { task_id: 't-10' },
  },
  {
    id: 'act-21',
    type: 'score_change',
    title: 'Readiness score updated',
    description: 'NeuralPay score increased from 72 to 75',
    actor: 'System',
    timestamp: '2025-01-29T09:15:00Z',
    metadata: { startup_id: 'startup-neuralpay', previous_score: 72, new_score: 75 },
  },
  {
    id: 'act-22',
    type: 'chat_message',
    title: 'Chat message sent',
    description: 'New message in "Financial model review" thread',
    actor: 'Sarah Chen',
    timestamp: '2025-02-06T09:00:00Z',
    metadata: { thread_id: 'thread-2' },
  },
  {
    id: 'act-23',
    type: 'match_saved',
    title: 'Match saved',
    description: 'General Catalyst match saved to shortlist',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T12:25:00Z',
    metadata: { match_id: 'match-1' },
  },
  {
    id: 'act-24',
    type: 'task_status_changed',
    title: 'Task status updated',
    description: '"Add competitive analysis slide" set to in progress',
    actor: 'Sarah Chen',
    timestamp: '2025-02-05T10:00:00Z',
    metadata: { task_id: 't-2' },
  },
  {
    id: 'act-25',
    type: 'file_upload',
    title: 'Document uploaded',
    description: 'Customer Case Study - Acme Corp.pdf was uploaded',
    actor: 'Sarah Chen',
    timestamp: '2025-02-04T15:20:00Z',
    metadata: { document_id: 'doc-10' },
  },
  {
    id: 'act-26',
    type: 'profile_update',
    title: 'Metrics updated',
    description: 'Latest metrics synced from Stripe and QuickBooks',
    actor: 'System',
    timestamp: '2025-02-03T08:00:00Z',
    metadata: { startup_id: 'startup-neuralpay' },
  },
  {
    id: 'act-27',
    type: 'match_passed',
    title: 'Match passed',
    description: 'AgriBot match (48 score) was passed',
    actor: 'Sarah Chen',
    timestamp: '2025-01-29T10:00:00Z',
    metadata: { match_id: 'match-13' },
  },
  {
    id: 'act-28',
    type: 'program_enrollment',
    title: 'Program enrollment',
    description: 'NeuralPay enrolled in Frictionless Series A Bootcamp',
    actor: 'Sarah Chen',
    timestamp: '2025-01-06T09:00:00Z',
    metadata: { program_id: 'prog-2' },
  },
  {
    id: 'act-29',
    type: 'assessment_run',
    title: 'Assessment completed',
    description: 'Run #1 completed for NeuralPay - score 68',
    actor: 'System',
    timestamp: '2025-01-15T10:00:00Z',
    metadata: { run_id: 'ar-1', startup_id: 'startup-neuralpay' },
  },
  {
    id: 'act-30',
    type: 'login',
    title: 'User logged in',
    description: 'Sarah Chen logged in from San Francisco',
    actor: 'Sarah Chen',
    timestamp: '2025-02-10T08:30:00Z',
    metadata: {},
  },
];
