export interface DummyMatch {
  id: string;
  startup_org_id: string;
  capital_provider_org_id: string;
  overall_score: number;
  score_delta: number;
  match_date: string;
  status: 'new' | 'viewed' | 'saved' | 'contacted' | 'passed';
  breakdown: Array<{
    dimension: string;
    score: number;
    weight: number;
    detail: string;
  }>;
  ai_explanation: string;
}

export const dummyMatches: DummyMatch[] = [
  {
    id: 'match-1',
    startup_org_id: 'startup-neuralpay',
    capital_provider_org_id: 'investor-gc',
    overall_score: 89,
    score_delta: 2,
    match_date: '2025-02-10T14:32:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 92, weight: 0.2, detail: 'Fintech is a core focus for General Catalyst.' },
      { dimension: 'stage_fit', score: 88, weight: 0.15, detail: 'Series A is within their sweet spot.' },
      { dimension: 'thesis_alignment', score: 90, weight: 0.2, detail: 'Strong alignment with payments infrastructure thesis.' },
      { dimension: 'check_size_fit', score: 85, weight: 0.1, detail: '$10M raise fits their $5M–$25M range.' },
      { dimension: 'traction_match', score: 91, weight: 0.2, detail: '$5M ARR and strong metrics exceed typical bar.' },
      { dimension: 'team_quality', score: 87, weight: 0.1, detail: 'Ex-Stripe founder team is compelling.' },
      { dimension: 'market_size', score: 88, weight: 0.05, detail: 'B2B payments is a $50B+ TAM.' },
    ],
    ai_explanation: 'NeuralPay is an excellent fit for General Catalyst. Their fintech thesis and Series A focus align perfectly. The ex-Stripe founding team and strong unit economics make this a high-conviction match.',
  },
  {
    id: 'match-2',
    startup_org_id: 'startup-neuralpay',
    capital_provider_org_id: 'investor-a16z',
    overall_score: 87,
    score_delta: 3,
    match_date: '2025-02-09T11:15:00Z',
    status: 'contacted',
    breakdown: [
      { dimension: 'sector_fit', score: 90, weight: 0.2, detail: 'Payments infrastructure is core a16z.' },
      { dimension: 'stage_fit', score: 85, weight: 0.15, detail: 'Series A fits their deployment profile.' },
      { dimension: 'thesis_alignment', score: 88, weight: 0.2, detail: 'Platform play with network effects.' },
      { dimension: 'check_size_fit', score: 75, weight: 0.1, detail: 'They often write larger checks at this stage.' },
      { dimension: 'traction_match', score: 92, weight: 0.2, detail: 'Strong MRR growth and NRR.' },
      { dimension: 'team_quality', score: 90, weight: 0.1, detail: 'Technical founders with domain expertise.' },
      { dimension: 'market_size', score: 91, weight: 0.05, detail: 'Large and growing TAM.' },
    ],
    ai_explanation: 'a16z has backed Stripe, Plaid, and other fintech infrastructure. NeuralPay\'s technical moat and platform approach fit their investment philosophy well.',
  },
  {
    id: 'match-3',
    startup_org_id: 'startup-datavault',
    capital_provider_org_id: 'investor-sequoia',
    overall_score: 94,
    score_delta: 1,
    match_date: '2025-02-08T09:45:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 95, weight: 0.2, detail: 'Cybersecurity and data compliance is strategic.' },
      { dimension: 'stage_fit', score: 93, weight: 0.15, detail: 'Series B with clear path to IPO.' },
      { dimension: 'thesis_alignment', score: 95, weight: 0.2, detail: 'Durable, category-defining business.' },
      { dimension: 'check_size_fit', score: 92, weight: 0.1, detail: 'Fits their growth stage deployment.' },
      { dimension: 'traction_match', score: 96, weight: 0.2, detail: '$28M ARR, profitable, strong retention.' },
      { dimension: 'team_quality', score: 94, weight: 0.1, detail: 'Palantir/McKinsey pedigree.' },
      { dimension: 'market_size', score: 95, weight: 0.05, detail: 'Regulatory tailwinds expanding TAM.' },
    ],
    ai_explanation: 'DataVault is exactly the type of durable, category-defining company Sequoia backs. Exceptional metrics and team. Strong IPO candidate.',
  },
  {
    id: 'match-4',
    startup_org_id: 'startup-greengrid',
    capital_provider_org_id: 'investor-yc',
    overall_score: 72,
    score_delta: 5,
    match_date: '2025-02-07T16:20:00Z',
    status: 'viewed',
    breakdown: [
      { dimension: 'sector_fit', score: 88, weight: 0.2, detail: 'Cleantech is a YC focus area.' },
      { dimension: 'stage_fit', score: 85, weight: 0.15, detail: 'Seed aligns with YC Continuity.' },
      { dimension: 'thesis_alignment', score: 78, weight: 0.2, detail: 'B2B utilities is less typical for YC.' },
      { dimension: 'check_size_fit', score: 65, weight: 0.1, detail: 'YC standard is $500K; may need other investors.' },
      { dimension: 'traction_match', score: 62, weight: 0.2, detail: 'Early revenue, limited customer base.' },
      { dimension: 'team_quality', score: 75, weight: 0.1, detail: 'Solid utility background.' },
      { dimension: 'market_size', score: 80, weight: 0.05, detail: 'Large climate opportunity.' },
    ],
    ai_explanation: 'GreenGrid fits YC\'s climate thesis. Seed stage is right. Consider applying to a batch for network and follow-on introductions.',
  },
  {
    id: 'match-5',
    startup_org_id: 'startup-medflow',
    capital_provider_org_id: 'investor-yc',
    overall_score: 58,
    score_delta: 2,
    match_date: '2025-02-06T10:00:00Z',
    status: 'new',
    breakdown: [
      { dimension: 'sector_fit', score: 82, weight: 0.2, detail: 'Healthtech is a core YC vertical.' },
      { dimension: 'stage_fit', score: 90, weight: 0.15, detail: 'Pre-seed is ideal for YC.' },
      { dimension: 'thesis_alignment', score: 65, weight: 0.2, detail: 'Hospital sales cycles are long.' },
      { dimension: 'check_size_fit', score: 88, weight: 0.1, detail: 'YC standard deal fits.' },
      { dimension: 'traction_match', score: 38, weight: 0.2, detail: 'Limited pilots, pre-revenue profile.' },
      { dimension: 'team_quality', score: 72, weight: 0.1, detail: 'Physician-founder is credible.' },
      { dimension: 'market_size', score: 85, weight: 0.05, detail: 'Large healthcare admin market.' },
    ],
    ai_explanation: 'MedFlow is early but healthtech and physician-founder could resonate. Strengthen pitch deck and add more pilot data before applying.',
  },
  {
    id: 'match-6',
    startup_org_id: 'startup-shopsphere',
    capital_provider_org_id: 'investor-accel',
    overall_score: 71,
    score_delta: 4,
    match_date: '2025-02-05T14:30:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 85, weight: 0.2, detail: 'E-commerce platform fits Accel\'s portfolio.' },
      { dimension: 'stage_fit', score: 82, weight: 0.15, detail: 'Seed/early A is their focus.' },
      { dimension: 'thesis_alignment', score: 78, weight: 0.2, detail: 'B2B SaaS for D2C brands.' },
      { dimension: 'check_size_fit', score: 70, weight: 0.1, detail: 'Slightly below typical check size.' },
      { dimension: 'traction_match', score: 65, weight: 0.2, detail: '$1.2M ARR with decent churn.' },
      { dimension: 'team_quality', score: 72, weight: 0.1, detail: 'Ex-Shopify founder.' },
      { dimension: 'market_size', score: 75, weight: 0.05, detail: 'Competitive but large TAM.' },
    ],
    ai_explanation: 'ShopSphere addresses Shopify limitations for scaling brands. Accel has backed similar e-commerce infra. Improve churn narrative.',
  },
  {
    id: 'match-7',
    startup_org_id: 'startup-cloudnine',
    capital_provider_org_id: 'investor-index',
    overall_score: 80,
    score_delta: 3,
    match_date: '2025-02-04T11:00:00Z',
    status: 'contacted',
    breakdown: [
      { dimension: 'sector_fit', score: 90, weight: 0.2, detail: 'DevOps/SaaS is Index core.' },
      { dimension: 'stage_fit', score: 85, weight: 0.15, detail: 'Series A fits their profile.' },
      { dimension: 'thesis_alignment', score: 82, weight: 0.2, detail: 'Developer tools with strong NRR.' },
      { dimension: 'check_size_fit', score: 78, weight: 0.1, detail: 'Check size in range.' },
      { dimension: 'traction_match', score: 88, weight: 0.2, detail: '$4.2M ARR, 400+ customers.' },
      { dimension: 'team_quality', score: 80, weight: 0.1, detail: 'Ex-AWS, ex-Datadog.' },
      { dimension: 'market_size', score: 82, weight: 0.05, detail: 'DevOps market expanding.' },
    ],
    ai_explanation: 'Index has backed Notion, Figma, and developer tools. CloudNine\'s platform approach and traction align well with their thesis.',
  },
  {
    id: 'match-8',
    startup_org_id: 'startup-financeai',
    capital_provider_org_id: 'investor-gc',
    overall_score: 88,
    score_delta: 2,
    match_date: '2025-02-03T09:15:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 92, weight: 0.2, detail: 'Fintech/SMB is core GC.' },
      { dimension: 'stage_fit', score: 87, weight: 0.15, detail: 'Series A fits.' },
      { dimension: 'thesis_alignment', score: 90, weight: 0.2, detail: 'AI + SMB workflow automation.' },
      { dimension: 'check_size_fit', score: 85, weight: 0.1, detail: 'Right check size.' },
      { dimension: 'traction_match', score: 91, weight: 0.2, detail: '$3.8M ARR, 95% retention.' },
      { dimension: 'team_quality', score: 86, weight: 0.1, detail: 'Ex-Intuit, CPA founder.' },
      { dimension: 'market_size', score: 88, weight: 0.05, detail: 'Massive SMB market.' },
    ],
    ai_explanation: 'FinanceAI\'s retention and unit economics are exceptional. GC has backed similar SMB fintech. Strong match.',
  },
  {
    id: 'match-9',
    startup_org_id: 'startup-biogenesis',
    capital_provider_org_id: 'investor-founders',
    overall_score: 85,
    score_delta: 2,
    match_date: '2025-02-02T15:45:00Z',
    status: 'viewed',
    breakdown: [
      { dimension: 'sector_fit', score: 92, weight: 0.2, detail: 'Biotech is Founders Fund focus.' },
      { dimension: 'stage_fit', score: 84, weight: 0.15, detail: 'Series B fits their range.' },
      { dimension: 'thesis_alignment', score: 90, weight: 0.2, detail: 'Frontier tech, contrarian bet.' },
      { dimension: 'check_size_fit', score: 82, weight: 0.1, detail: 'Within check range.' },
      { dimension: 'traction_match', score: 85, weight: 0.2, detail: '$12M ARR, breakthrough results.' },
      { dimension: 'team_quality', score: 88, weight: 0.1, detail: 'PhD Stanford, ex-Ginkgo.' },
      { dimension: 'market_size', score: 90, weight: 0.05, detail: 'Sustainability tailwinds.' },
    ],
    ai_explanation: 'BioGenesis is exactly the type of frontier biotech Founders Fund backs. Contrarian, technical, category-defining potential.',
  },
  {
    id: 'match-10',
    startup_org_id: 'startup-quantumleap',
    capital_provider_org_id: 'investor-tiger',
    overall_score: 91,
    score_delta: 1,
    match_date: '2025-02-01T12:30:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 90, weight: 0.2, detail: 'Deeptech fits Tiger\'s growth thesis.' },
      { dimension: 'stage_fit', score: 92, weight: 0.15, detail: 'Series C is their sweet spot.' },
      { dimension: 'thesis_alignment', score: 88, weight: 0.2, detail: 'Category leader in quantum software.' },
      { dimension: 'check_size_fit', score: 95, weight: 0.1, detail: 'Large checks for growth.' },
      { dimension: 'traction_match', score: 94, weight: 0.2, detail: '$15M ARR, partnerships with IBM/Google.' },
      { dimension: 'team_quality', score: 90, weight: 0.1, detail: 'MIT/Stanford PhD team.' },
      { dimension: 'market_size', score: 92, weight: 0.05, detail: 'Quantum computing TAM growing fast.' },
    ],
    ai_explanation: 'QuantumLeap is a growth-stage category leader. Tiger invests in companies like Databricks at this stage. Strong fit.',
  },
  {
    id: 'match-11',
    startup_org_id: 'startup-eduspark',
    capital_provider_org_id: 'investor-lightspeed',
    overall_score: 74,
    score_delta: 4,
    match_date: '2025-01-31T10:00:00Z',
    status: 'new',
    breakdown: [
      { dimension: 'sector_fit', score: 78, weight: 0.2, detail: 'Edtech is less core for Lightspeed.' },
      { dimension: 'stage_fit', score: 85, weight: 0.15, detail: 'Seed fits.' },
      { dimension: 'thesis_alignment', score: 72, weight: 0.2, detail: 'B2B2C education.' },
      { dimension: 'check_size_fit', score: 75, weight: 0.1, detail: 'Check size in range.' },
      { dimension: 'traction_match', score: 78, weight: 0.2, detail: '$680K ARR, 50 schools.' },
      { dimension: 'team_quality', score: 80, weight: 0.1, detail: 'Teacher-founder credibility.' },
      { dimension: 'market_size', score: 82, weight: 0.05, detail: 'K-12 is large market.' },
    ],
    ai_explanation: 'EduSpark has solid traction. Lightspeed does consumer/enterprise; edtech is adjacent. Worth a conversation.',
  },
  {
    id: 'match-12',
    startup_org_id: 'startup-cybershield',
    capital_provider_org_id: 'investor-a16z',
    overall_score: 82,
    score_delta: 3,
    match_date: '2025-01-30T14:00:00Z',
    status: 'viewed',
    breakdown: [
      { dimension: 'sector_fit', score: 92, weight: 0.2, detail: 'Cybersecurity is core a16z.' },
      { dimension: 'stage_fit', score: 85, weight: 0.15, detail: 'Series A fits.' },
      { dimension: 'thesis_alignment', score: 88, weight: 0.2, detail: 'Zero-trust, endpoint security.' },
      { dimension: 'check_size_fit', score: 72, weight: 0.1, detail: 'May be below typical check.' },
      { dimension: 'traction_match', score: 80, weight: 0.2, detail: '$2.1M ARR, 85 customers.' },
      { dimension: 'team_quality', score: 85, weight: 0.1, detail: 'Ex-CrowdStrike CISO.' },
      { dimension: 'market_size', score: 88, weight: 0.05, detail: 'Remote work tailwinds.' },
    ],
    ai_explanation: 'CyberShield fits a16z\'s security thesis. CISO founder and zero-trust angle are compelling. Consider raising round size.',
  },
  {
    id: 'match-13',
    startup_org_id: 'startup-agribot',
    capital_provider_org_id: 'investor-yc',
    overall_score: 48,
    score_delta: -2,
    match_date: '2025-01-29T09:30:00Z',
    status: 'passed',
    breakdown: [
      { dimension: 'sector_fit', score: 72, weight: 0.2, detail: 'Agtech is a YC vertical.' },
      { dimension: 'stage_fit', score: 90, weight: 0.15, detail: 'Pre-seed fits.' },
      { dimension: 'thesis_alignment', score: 55, weight: 0.2, detail: 'Hardware heavy, long cycles.' },
      { dimension: 'check_size_fit', score: 85, weight: 0.1, detail: 'YC standard deal.' },
      { dimension: 'traction_match', score: 28, weight: 0.2, detail: 'Very early, 2 farm pilots.' },
      { dimension: 'team_quality', score: 52, weight: 0.1, detail: 'Farmer-founder, limited team.' },
      { dimension: 'market_size', score: 65, weight: 0.05, detail: 'Large ag market.' },
    ],
    ai_explanation: 'AgriBot is too early for strong match. Hardware and ag cycles are challenging. Consider more pilot data and technical validation.',
  },
  {
    id: 'match-14',
    startup_org_id: 'startup-foodtech',
    capital_provider_org_id: 'investor-accel',
    overall_score: 68,
    score_delta: 3,
    match_date: '2025-01-28T11:45:00Z',
    status: 'new',
    breakdown: [
      { dimension: 'sector_fit', score: 65, weight: 0.2, detail: 'Foodtech/supply chain is adjacent.' },
      { dimension: 'stage_fit', score: 80, weight: 0.15, detail: 'Seed fits.' },
      { dimension: 'thesis_alignment', score: 62, weight: 0.2, detail: 'B2B supply chain software.' },
      { dimension: 'check_size_fit', score: 70, weight: 0.1, detail: 'Check size on the lower end.' },
      { dimension: 'traction_match', score: 70, weight: 0.2, detail: '$580K ARR, 25 customers.' },
      { dimension: 'team_quality', score: 72, weight: 0.1, detail: 'Ex-General Mills.' },
      { dimension: 'market_size', score: 75, weight: 0.05, detail: 'Traceability regulatory tailwinds.' },
    ],
    ai_explanation: 'FoodTech Labs has solid early traction. Accel backs B2B software; food supply chain is a niche but growing area. Improve market sizing.',
  },
  {
    id: 'match-15',
    startup_org_id: 'startup-proptech',
    capital_provider_org_id: 'investor-index',
    overall_score: 62,
    score_delta: 1,
    match_date: '2025-01-27T15:00:00Z',
    status: 'passed',
    breakdown: [
      { dimension: 'sector_fit', score: 60, weight: 0.2, detail: 'PropTech is less Index focus.' },
      { dimension: 'stage_fit', score: 78, weight: 0.15, detail: 'Seed fits.' },
      { dimension: 'thesis_alignment', score: 58, weight: 0.2, detail: 'Property management is niche.' },
      { dimension: 'check_size_fit', score: 68, weight: 0.1, detail: 'Check size OK.' },
      { dimension: 'traction_match', score: 58, weight: 0.2, detail: '$920K ARR but 5.2% churn is concern.' },
      { dimension: 'team_quality', score: 65, weight: 0.1, detail: 'Industry experience.' },
      { dimension: 'market_size', score: 72, weight: 0.05, detail: 'Large multifamily market.' },
    ],
    ai_explanation: 'PropTech Solutions needs to address churn before strong investor interest. Index typically prefers higher-growth SaaS.',
  },
  {
    id: 'match-16',
    startup_org_id: 'startup-urbanmobility',
    capital_provider_org_id: 'investor-yc',
    overall_score: 55,
    score_delta: 2,
    match_date: '2025-01-26T10:30:00Z',
    status: 'new',
    breakdown: [
      { dimension: 'sector_fit', score: 75, weight: 0.2, detail: 'Mobility/urban tech is YC.' },
      { dimension: 'stage_fit', score: 92, weight: 0.15, detail: 'Pre-seed is ideal for YC.' },
      { dimension: 'thesis_alignment', score: 52, weight: 0.2, detail: 'B2B for operators is niche.' },
      { dimension: 'check_size_fit', score: 88, weight: 0.1, detail: 'YC deal fits.' },
      { dimension: 'traction_match', score: 38, weight: 0.2, detail: '3 city pilots, pre-revenue.' },
      { dimension: 'team_quality', score: 58, weight: 0.1, detail: 'Ex-Lime background.' },
      { dimension: 'market_size', score: 70, weight: 0.05, detail: 'Micromobility market recovering.' },
    ],
    ai_explanation: 'UrbanMobility is very early. Ex-Lime founder is a positive. YC could provide runway to prove model. Strengthen pilot outcomes.',
  },
  {
    id: 'match-17',
    startup_org_id: 'startup-datavault',
    capital_provider_org_id: 'investor-tiger',
    overall_score: 90,
    score_delta: 0,
    match_date: '2025-01-25T09:00:00Z',
    status: 'contacted',
    breakdown: [
      { dimension: 'sector_fit', score: 88, weight: 0.2, detail: 'Enterprise software is Tiger focus.' },
      { dimension: 'stage_fit', score: 92, weight: 0.15, detail: 'Series B fits growth profile.' },
      { dimension: 'thesis_alignment', score: 90, weight: 0.2, detail: 'Category-defining, durable.' },
      { dimension: 'check_size_fit', score: 85, weight: 0.1, detail: 'May need larger raise for Tiger.' },
      { dimension: 'traction_match', score: 95, weight: 0.2, detail: '$28M ARR, profitable.' },
      { dimension: 'team_quality', score: 90, weight: 0.1, detail: 'Elite team.' },
      { dimension: 'market_size', score: 92, weight: 0.05, detail: 'Regulatory tailwinds.' },
    ],
    ai_explanation: 'DataVault is a growth-stage category leader. Tiger backs companies like this for scale. Consider growth round.',
  },
  {
    id: 'match-18',
    startup_org_id: 'startup-quantumleap',
    capital_provider_org_id: 'investor-softbank',
    overall_score: 88,
    score_delta: 1,
    match_date: '2025-01-24T16:00:00Z',
    status: 'viewed',
    breakdown: [
      { dimension: 'sector_fit', score: 90, weight: 0.2, detail: 'AI/quantum fits Vision Fund.' },
      { dimension: 'stage_fit', score: 92, weight: 0.15, detail: 'Series C is growth focus.' },
      { dimension: 'thesis_alignment', score: 88, weight: 0.2, detail: 'Frontier tech, category leader.' },
      { dimension: 'check_size_fit', score: 78, weight: 0.1, detail: 'SoftBank typically writes larger checks.' },
      { dimension: 'traction_match', score: 92, weight: 0.2, detail: '$15M ARR, partnerships.' },
      { dimension: 'team_quality', score: 90, weight: 0.1, detail: 'PhD team.' },
      { dimension: 'market_size', score: 92, weight: 0.05, detail: 'Quantum computing opportunity.' },
    ],
    ai_explanation: 'QuantumLeap could fit SoftBank\'s frontier tech thesis. Their typical check size is larger—consider if raising a mega-round.',
  },
  {
    id: 'match-19',
    startup_org_id: 'startup-neuralpay',
    capital_provider_org_id: 'investor-sequoia',
    overall_score: 86,
    score_delta: 2,
    match_date: '2025-01-23T13:20:00Z',
    status: 'saved',
    breakdown: [
      { dimension: 'sector_fit', score: 90, weight: 0.2, detail: 'Fintech is Sequoia focus.' },
      { dimension: 'stage_fit', score: 88, weight: 0.15, detail: 'Series A fits.' },
      { dimension: 'thesis_alignment', score: 85, weight: 0.2, detail: 'Payments infrastructure.' },
      { dimension: 'check_size_fit', score: 85, weight: 0.1, detail: 'Check size in range.' },
      { dimension: 'traction_match', score: 90, weight: 0.2, detail: 'Strong metrics.' },
      { dimension: 'team_quality', score: 88, weight: 0.1, detail: 'Ex-Stripe team.' },
      { dimension: 'market_size', score: 88, weight: 0.05, detail: 'Large B2B payments TAM.' },
    ],
    ai_explanation: 'NeuralPay aligns with Sequoia\'s fintech and infrastructure bets. Stripe, Square, and others in portfolio. Strong fit.',
  },
  {
    id: 'match-20',
    startup_org_id: 'startup-financeai',
    capital_provider_org_id: 'investor-lightspeed',
    overall_score: 81,
    score_delta: 3,
    match_date: '2025-01-22T11:00:00Z',
    status: 'new',
    breakdown: [
      { dimension: 'sector_fit', score: 85, weight: 0.2, detail: 'Fintech/SMB software.' },
      { dimension: 'stage_fit', score: 88, weight: 0.15, detail: 'Series A fits.' },
      { dimension: 'thesis_alignment', score: 82, weight: 0.2, detail: 'B2B SaaS with strong retention.' },
      { dimension: 'check_size_fit', score: 82, weight: 0.1, detail: 'Check size OK.' },
      { dimension: 'traction_match', score: 88, weight: 0.2, detail: '$3.8M ARR, 95% retention.' },
      { dimension: 'team_quality', score: 80, weight: 0.1, detail: 'Ex-Intuit founder.' },
      { dimension: 'market_size', score: 85, weight: 0.05, detail: 'Massive SMB market.' },
    ],
    ai_explanation: 'FinanceAI has exceptional unit economics. Lightspeed backs B2B software with strong retention. Worth exploring.',
  },
];
