export interface DummyNotification {
  id: string;
  type: 'score_change' | 'new_match' | 'task_due' | 'message' | 'system';
  title: string;
  description: string;
  read: boolean;
  created_at: string;
  link?: string;
}

export const dummyNotifications: DummyNotification[] = [
  {
    id: 'notif-1',
    type: 'score_change',
    title: 'Readiness score improved',
    description: 'NeuralPay score increased from 79 to 82. You moved into the "Strong" badge tier.',
    read: false,
    created_at: '2025-02-10T16:00:00Z',
    link: '/startup/neuralpay/assessment',
  },
  {
    id: 'notif-2',
    type: 'new_match',
    title: 'New high-score match',
    description: 'General Catalyst (89 match score) — Strong fintech fit. View match details.',
    read: false,
    created_at: '2025-02-10T14:35:00Z',
    link: '/matches/match-1',
  },
  {
    id: 'notif-3',
    type: 'task_due',
    title: 'Task due soon',
    description: '"Add competitive analysis slide" is due in 7 days.',
    read: false,
    created_at: '2025-02-10T09:00:00Z',
    link: '/tasks/t-2',
  },
  {
    id: 'notif-4',
    type: 'message',
    title: 'Chat reply',
    description: 'You received a reply in "Pitch deck feedback" thread.',
    read: true,
    created_at: '2025-02-10T10:16:00Z',
    link: '/chat/thread-1',
  },
  {
    id: 'notif-5',
    type: 'new_match',
    title: 'Match update',
    description: 'Andreessen Horowitz match (87 score) — You marked as contacted.',
    read: true,
    created_at: '2025-02-09T14:00:00Z',
    link: '/matches/match-2',
  },
  {
    id: 'notif-6',
    type: 'score_change',
    title: 'Readiness score updated',
    description: 'NeuralPay score increased from 75 to 79.',
    read: true,
    created_at: '2025-02-05T11:45:00Z',
    link: '/startup/neuralpay/assessment',
  },
  {
    id: 'notif-7',
    type: 'task_due',
    title: 'Task overdue',
    description: '"Upload cap table" was due yesterday. Update status or extend due date.',
    read: false,
    created_at: '2025-02-06T00:00:00Z',
    link: '/tasks/t-25',
  },
  {
    id: 'notif-8',
    type: 'system',
    title: 'Document validated',
    description: 'NeuralPay Pitch Deck Q1 2025.pdf passed validation.',
    read: true,
    created_at: '2025-02-08T10:32:00Z',
    link: '/documents/doc-1',
  },
  {
    id: 'notif-9',
    type: 'new_match',
    title: 'New match available',
    description: 'Sequoia Capital (86 match score) — Fintech focus. View match.',
    read: true,
    created_at: '2025-01-23T13:25:00Z',
    link: '/matches/match-19',
  },
  {
    id: 'notif-10',
    type: 'message',
    title: 'Chat reply',
    description: 'You received a reply in "Financial model review" thread.',
    read: true,
    created_at: '2025-02-07T11:22:00Z',
    link: '/chat/thread-2',
  },
  {
    id: 'notif-11',
    type: 'task_due',
    title: 'Task due tomorrow',
    description: '"Add unit economics breakdown" is due tomorrow.',
    read: false,
    created_at: '2025-02-10T08:00:00Z',
    link: '/tasks/t-31',
  },
  {
    id: 'notif-12',
    type: 'system',
    title: 'Program reminder',
    description: 'Frictionless Seed Accelerator 2025 applications close in 2 weeks.',
    read: false,
    created_at: '2025-02-09T12:00:00Z',
    link: '/programs/prog-1',
  },
  {
    id: 'notif-13',
    type: 'score_change',
    title: 'Readiness score updated',
    description: 'NeuralPay score increased from 72 to 75.',
    read: true,
    created_at: '2025-01-29T09:15:00Z',
    link: '/startup/neuralpay/assessment',
  },
  {
    id: 'notif-14',
    type: 'new_match',
    title: 'Match saved',
    description: 'You saved the General Catalyst match to your shortlist.',
    read: true,
    created_at: '2025-02-10T12:25:00Z',
    link: '/matches/match-1',
  },
  {
    id: 'notif-15',
    type: 'system',
    title: 'Scheduled maintenance',
    description: 'Platform maintenance planned for Sunday 2am–4am PT. Some features may be unavailable.',
    read: true,
    created_at: '2025-02-08T18:00:00Z',
    link: '/',
  },
];
