export interface DummyStartup {
  org_id: string;
  org: {
    id: string;
    name: string;
    org_type: 'startup';
    logo_url: string;
    website: string;
    slug: string;
    description: string;
  };
  sector: { code: string; name: string };
  subsector: { code: string; name: string };
  stage: string;
  business_model: string;
  founded_year: number;
  employee_count: number;
  hq_location: { city: string; state: string; country: string };
  short_summary: string;
  pitch_summary: string;
  current_Readiness_score: number;
  score_delta: number;
  latest_metrics: {
    mrr: number;
    arr: number;
    revenue_ttm: number;
    gross_margin_pct: number;
    burn_monthly: number;
    runway_months: number;
    headcount: number;
    customer_count: number;
    cac: number;
    ltv: number;
    churn_rate_pct: number;
    nps_score: number;
  };
  tags: string[];
  founders: Array<{
    full_name: string;
    title: string;
    photo_url: string;
    linkedin_url?: string;
    bio: string;
    is_primary: boolean;
  }>;
  assessment: {
    overall_score: number;
    badge: string;
    categories: Array<{ name: string; score: number; delta: number; weight: number }>;
    missing_data: Array<{ item: string; severity: 'high' | 'medium' | 'low' }>;
  };
}

const ASSESSMENT_CATEGORIES = [
  'Storytelling & Pitch',
  'Founder & Team',
  'Product & Technology',
  'Foundational Setup',
  'Metrics & Financials',
  'Go-To-Market Strategy',
  'Traction & Validation',
];

function buildCategories(overall: number, deltas: number[]): Array<{ name: string; score: number; delta: number; weight: number }> {
  return ASSESSMENT_CATEGORIES.map((name, i) => ({
    name,
    score: Math.min(100, Math.max(0, overall + (deltas[i] ?? 0))),
    delta: deltas[i] ?? 0,
    weight: 1 / 7,
  }));
}

export const dummyStartups: DummyStartup[] = [
  {
    org_id: 'startup-neuralpay',
    org: {
      id: 'startup-neuralpay',
      name: 'NeuralPay',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=NeuralPay',
      website: 'https://neuralpay.io',
      slug: 'neuralpay',
      description: 'AI-powered payments infrastructure for B2B marketplaces.',
    },
    sector: { code: 'fintech', name: 'Fintech' },
    subsector: { code: 'payments', name: 'Payments' },
    stage: 'series_a',
    business_model: 'B2B SaaS',
    founded_year: 2021,
    employee_count: 42,
    hq_location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    short_summary: 'AI-driven payment orchestration reducing settlement times by 60%.',
    pitch_summary: 'NeuralPay provides intelligent payment infrastructure that uses machine learning to optimize routing, reduce fraud, and accelerate settlement for enterprise marketplaces. We process $2B+ monthly GMV across 200+ merchants.',
    current_Readiness_score: 82,
    score_delta: 3,
    latest_metrics: {
      mrr: 420000,
      arr: 5040000,
      revenue_ttm: 4850000,
      gross_margin_pct: 78,
      burn_monthly: 320000,
      runway_months: 18,
      headcount: 42,
      customer_count: 187,
      cac: 12000,
      ltv: 85000,
      churn_rate_pct: 2.1,
      nps_score: 62,
    },
    tags: ['AI', 'Payments', 'B2B', 'Enterprise'],
    founders: [
      {
        full_name: 'Sarah Chen',
        title: 'CEO & Co-Founder',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahChen',
        linkedin_url: 'https://linkedin.com/in/sarahchen',
        bio: 'Former Head of Payments at Stripe. 12 years in fintech.',
        is_primary: true,
      },
      {
        full_name: 'Marcus Webb',
        title: 'CTO & Co-Founder',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusWebb',
        bio: 'Ex-Google Brain. PhD ML from MIT.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 82,
      badge: 'strong',
      categories: buildCategories(82, [2, 0, 4, -1, 3, 2, 1]),
      missing_data: [{ item: 'Updated cap table', severity: 'low' }],
    },
  },
  {
    org_id: 'startup-greengrid',
    org: {
      id: 'startup-greengrid',
      name: 'GreenGrid',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=GreenGrid',
      website: 'https://greengrid.energy',
      slug: 'greengrid',
      description: 'Smart grid optimization software for renewable energy integration.',
    },
    sector: { code: 'cleantech', name: 'Cleantech' },
    subsector: { code: 'energy', name: 'Energy' },
    stage: 'seed',
    business_model: 'B2B SaaS',
    founded_year: 2022,
    employee_count: 18,
    hq_location: { city: 'Austin', state: 'TX', country: 'USA' },
    short_summary: 'AI-powered grid management for utilities adopting solar and wind.',
    pitch_summary: 'GreenGrid helps utilities integrate renewables at scale. Our platform predicts demand, optimizes storage, and reduces curtailment by 40%. Currently deployed at 3 municipal utilities.',
    current_Readiness_score: 65,
    score_delta: 5,
    latest_metrics: {
      mrr: 45000,
      arr: 540000,
      revenue_ttm: 380000,
      gross_margin_pct: 65,
      burn_monthly: 95000,
      runway_months: 14,
      headcount: 18,
      customer_count: 8,
      cac: 28000,
      ltv: 320000,
      churn_rate_pct: 0,
      nps_score: 48,
    },
    tags: ['Climate', 'Utilities', 'AI', 'B2B'],
    founders: [
      {
        full_name: 'Elena Rodriguez',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ElenaRodriguez',
        bio: 'Former utility exec. 15 years in energy.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 65,
      badge: 'developing',
      categories: buildCategories(65, [-3, 2, 4, 0, -2, 1, -1]),
      missing_data: [
        { item: 'Financial projections', severity: 'medium' },
        { item: 'Competitive landscape', severity: 'low' },
      ],
    },
  },
  {
    org_id: 'startup-medflow',
    org: {
      id: 'startup-medflow',
      name: 'MedFlow AI',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=MedFlowAI',
      website: 'https://medflow.ai',
      slug: 'medflow-ai',
      description: 'AI workflow automation for hospital operations.',
    },
    sector: { code: 'healthtech', name: 'Healthtech' },
    subsector: { code: 'hospital_ops', name: 'Hospital Operations' },
    stage: 'pre_seed',
    business_model: 'B2B SaaS',
    founded_year: 2023,
    employee_count: 7,
    hq_location: { city: 'Boston', state: 'MA', country: 'USA' },
    short_summary: 'Reduce administrative burden in hospitals with AI.',
    pitch_summary: 'MedFlow AI automates scheduling, prior auth, and discharge documentation. Pilot with 2 community hospitals showed 30% reduction in admin time. Seeking pre-seed to complete pilots.',
    current_Readiness_score: 45,
    score_delta: -2,
    latest_metrics: {
      mrr: 8000,
      arr: 96000,
      revenue_ttm: 42000,
      gross_margin_pct: 52,
      burn_monthly: 55000,
      runway_months: 8,
      headcount: 7,
      customer_count: 2,
      cac: 15000,
      ltv: 75000,
      churn_rate_pct: 0,
      nps_score: 35,
    },
    tags: ['Healthcare', 'AI', 'Workflow'],
    founders: [
      {
        full_name: 'Dr. James Okonkwo',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JamesOkonkwo',
        bio: 'Former ER physician. MBA from Wharton.',
        is_primary: true,
      },
      {
        full_name: 'Priya Sharma',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaSharma',
        bio: 'Ex-Google Health. ML engineer.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 45,
      badge: 'early',
      categories: buildCategories(45, [-5, -2, 0, -3, -8, -4, -6]),
      missing_data: [
        { item: 'Pitch deck', severity: 'high' },
        { item: 'Financial model', severity: 'high' },
        { item: 'Team bios', severity: 'medium' },
      ],
    },
  },
  {
    org_id: 'startup-datavault',
    org: {
      id: 'startup-datavault',
      name: 'DataVault',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=DataVault',
      website: 'https://datavault.io',
      slug: 'datavault',
      description: 'Enterprise data sovereignty and compliance platform.',
    },
    sector: { code: 'cybersecurity', name: 'Cybersecurity' },
    subsector: { code: 'data_protection', name: 'Data Protection' },
    stage: 'series_b',
    business_model: 'B2B SaaS',
    founded_year: 2019,
    employee_count: 95,
    hq_location: { city: 'New York', state: 'NY', country: 'USA' },
    short_summary: 'Keep data in-region while enabling global analytics.',
    pitch_summary: 'DataVault enables enterprises to comply with GDPR, CCPA, and sector regulations without sacrificing analytics. Data never leaves the region. 50+ F500 customers. $28M ARR.',
    current_Readiness_score: 91,
    score_delta: 2,
    latest_metrics: {
      mrr: 2330000,
      arr: 28000000,
      revenue_ttm: 27500000,
      gross_margin_pct: 85,
      burn_monthly: 0,
      runway_months: 36,
      headcount: 95,
      customer_count: 52,
      cac: 45000,
      ltv: 380000,
      churn_rate_pct: 1.2,
      nps_score: 71,
    },
    tags: ['Compliance', 'Data', 'Enterprise', 'Security'],
    founders: [
      {
        full_name: 'Rebecca Kim',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RebeccaKim',
        bio: 'Ex-Palantir, ex-McKinsey. Stanford CS.',
        is_primary: true,
      },
      {
        full_name: 'David Park',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DavidPark',
        bio: 'Ex-AWS. Built data infrastructure at scale.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 91,
      badge: 'exceptional',
      categories: buildCategories(91, [1, 0, 2, 0, 1, 0, 1]),
      missing_data: [],
    },
  },
  {
    org_id: 'startup-shopsphere',
    org: {
      id: 'startup-shopsphere',
      name: 'ShopSphere',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=ShopSphere',
      website: 'https://shopsphere.com',
      slug: 'shopsphere',
      description: 'Headless commerce platform for D2C brands.',
    },
    sector: { code: 'ecommerce', name: 'E-commerce' },
    subsector: { code: 'platform', name: 'Platform' },
    stage: 'seed',
    business_model: 'B2B SaaS',
    founded_year: 2022,
    employee_count: 24,
    hq_location: { city: 'Los Angeles', state: 'CA', country: 'USA' },
    short_summary: 'Modern stack for D2C brands. Shopify alternative.',
    pitch_summary: 'ShopSphere provides headless commerce infrastructure for brands that outgrow Shopify. API-first, developer-friendly. 120+ brands. $1.2M ARR. Targeting $5M ARR in 18 months.',
    current_Readiness_score: 58,
    score_delta: 4,
    latest_metrics: {
      mrr: 100000,
      arr: 1200000,
      revenue_ttm: 980000,
      gross_margin_pct: 58,
      burn_monthly: 75000,
      runway_months: 12,
      headcount: 24,
      customer_count: 124,
      cac: 3200,
      ltv: 18500,
      churn_rate_pct: 4.2,
      nps_score: 42,
    },
    tags: ['E-commerce', 'D2C', 'SaaS'],
    founders: [
      {
        full_name: 'Alex Thompson',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexThompson',
        bio: 'Ex-Shopify. Founded 2 ecomm companies.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 58,
      badge: 'developing',
      categories: buildCategories(58, [-2, 0, 2, -4, -1, 3, 0]),
      missing_data: [
        { item: 'Competitive analysis', severity: 'medium' },
        { item: 'Unit economics detail', severity: 'medium' },
      ],
    },
  },
  {
    org_id: 'startup-cloudnine',
    org: {
      id: 'startup-cloudnine',
      name: 'CloudNine',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=CloudNine',
      website: 'https://cloudnine.io',
      slug: 'cloudnine',
      description: 'DevOps automation and observability platform.',
    },
    sector: { code: 'saas', name: 'SaaS' },
    subsector: { code: 'devtools', name: 'Developer Tools' },
    stage: 'series_a',
    business_model: 'B2B SaaS',
    founded_year: 2020,
    employee_count: 55,
    hq_location: { city: 'Seattle', state: 'WA', country: 'USA' },
    short_summary: 'One platform for CI/CD, monitoring, and incident response.',
    pitch_summary: 'CloudNine unifies DevOps workflows. From build to deploy to incident response. Reduces tool sprawl. 400+ engineering teams. $4.2M ARR. Strong NRR.',
    current_Readiness_score: 77,
    score_delta: 5,
    latest_metrics: {
      mrr: 350000,
      arr: 4200000,
      revenue_ttm: 3980000,
      gross_margin_pct: 82,
      burn_monthly: 180000,
      runway_months: 22,
      headcount: 55,
      customer_count: 412,
      cac: 4200,
      ltv: 52000,
      churn_rate_pct: 1.8,
      nps_score: 58,
    },
    tags: ['DevOps', 'SaaS', 'B2B'],
    founders: [
      {
        full_name: 'Jordan Lee',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JordanLee',
        bio: 'Ex-AWS, ex-Datadog. Built infra at scale.',
        is_primary: true,
      },
      {
        full_name: 'Taylor Morgan',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TaylorMorgan',
        bio: 'Ex-GitHub. Open source contributor.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 77,
      badge: 'strong',
      categories: buildCategories(77, [2, 1, 3, 0, 2, 1, 0]),
      missing_data: [{ item: 'Updated financials', severity: 'low' }],
    },
  },
  {
    org_id: 'startup-agribot',
    org: {
      id: 'startup-agribot',
      name: 'AgriBot',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=AgriBot',
      website: 'https://agribot.farm',
      slug: 'agribot',
      description: 'Autonomous field robots for precision agriculture.',
    },
    sector: { code: 'agtech', name: 'Agtech' },
    subsector: { code: 'robotics', name: 'Robotics' },
    stage: 'pre_seed',
    business_model: 'Hardware + SaaS',
    founded_year: 2023,
    employee_count: 5,
    hq_location: { city: 'Des Moines', state: 'IA', country: 'USA' },
    short_summary: 'Robots that weed and harvest. Reduce labor costs 40%.',
    pitch_summary: 'AgriBot deploys autonomous robots for weeding and selective harvest. Pilot with 2 farms showed 40% labor reduction. Seeking pre-seed for prototype scale.',
    current_Readiness_score: 32,
    score_delta: -3,
    latest_metrics: {
      mrr: 2000,
      arr: 24000,
      revenue_ttm: 18000,
      gross_margin_pct: 25,
      burn_monthly: 45000,
      runway_months: 5,
      headcount: 5,
      customer_count: 2,
      cac: 20000,
      ltv: 60000,
      churn_rate_pct: 0,
      nps_score: 28,
    },
    tags: ['Agriculture', 'Robotics', 'Hardware'],
    founders: [
      {
        full_name: 'Mike Johnson',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MikeJohnson',
        bio: '4th gen farmer. MIT robotics.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 32,
      badge: 'early',
      categories: buildCategories(32, [-10, -6, -4, -8, -12, -8, -10]),
      missing_data: [
        { item: 'Pitch deck', severity: 'high' },
        { item: 'Financial model', severity: 'high' },
        { item: 'Team bios', severity: 'high' },
        { item: 'Technical specs', severity: 'medium' },
      ],
    },
  },
  {
    org_id: 'startup-eduspark',
    org: {
      id: 'startup-eduspark',
      name: 'EduSpark',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=EduSpark',
      website: 'https://eduspark.io',
      slug: 'eduspark',
      description: 'Personalized learning paths for K-12.',
    },
    sector: { code: 'edtech', name: 'Edtech' },
    subsector: { code: 'k12', name: 'K-12' },
    stage: 'seed',
    business_model: 'B2B2C',
    founded_year: 2022,
    employee_count: 22,
    hq_location: { city: 'Chicago', state: 'IL', country: 'USA' },
    short_summary: 'Adaptive learning that improves outcomes 25%.',
    pitch_summary: 'EduSpark uses AI to create personalized learning paths. Used by 50 schools. Proven 25% improvement in standardized scores. $680K ARR. Expanding to 200 schools.',
    current_Readiness_score: 69,
    score_delta: 6,
    latest_metrics: {
      mrr: 57000,
      arr: 684000,
      revenue_ttm: 520000,
      gross_margin_pct: 72,
      burn_monthly: 65000,
      runway_months: 16,
      headcount: 22,
      customer_count: 52,
      cac: 8500,
      ltv: 42000,
      churn_rate_pct: 3.5,
      nps_score: 55,
    },
    tags: ['Education', 'AI', 'K-12'],
    founders: [
      {
        full_name: 'Rachel Green',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RachelGreen',
        bio: 'Former teacher. Stanford Ed Tech.',
        is_primary: true,
      },
      {
        full_name: 'Chris Wu',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChrisWu',
        bio: 'Ex-Khan Academy. ML for education.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 69,
      badge: 'promising',
      categories: buildCategories(69, [1, 2, 3, 0, 2, 1, 2]),
      missing_data: [{ item: 'Market sizing', severity: 'low' }],
    },
  },
  {
    org_id: 'startup-financeai',
    org: {
      id: 'startup-financeai',
      name: 'FinanceAI',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=FinanceAI',
      website: 'https://financeai.com',
      slug: 'financeai',
      description: 'AI-powered CFO assistant for SMBs.',
    },
    sector: { code: 'fintech', name: 'Fintech' },
    subsector: { code: 'accounting', name: 'Accounting' },
    stage: 'series_a',
    business_model: 'B2B SaaS',
    founded_year: 2021,
    employee_count: 48,
    hq_location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    short_summary: 'Automate bookkeeping, forecasting, and compliance.',
    pitch_summary: 'FinanceAI is an AI CFO for SMBs. Handles bookkeeping, cash flow forecasting, and tax prep. 2,400 customers. $3.8M ARR. 95% retention.',
    current_Readiness_score: 85,
    score_delta: 4,
    latest_metrics: {
      mrr: 317000,
      arr: 3800000,
      revenue_ttm: 3620000,
      gross_margin_pct: 80,
      burn_monthly: 220000,
      runway_months: 20,
      headcount: 48,
      customer_count: 2400,
      cac: 1800,
      ltv: 42000,
      churn_rate_pct: 1.5,
      nps_score: 68,
    },
    tags: ['Fintech', 'AI', 'SMB'],
    founders: [
      {
        full_name: 'Nina Patel',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NinaPatel',
        bio: 'Ex-Intuit, ex-KPMG. CPA, MBA.',
        is_primary: true,
      },
      {
        full_name: 'Omar Hassan',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=OmarHassan',
        bio: 'Ex-Stripe. NLP and automation.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 85,
      badge: 'strong',
      categories: buildCategories(85, [2, 1, 3, 0, 2, 1, 0]),
      missing_data: [],
    },
  },
  {
    org_id: 'startup-urbanmobility',
    org: {
      id: 'startup-urbanmobility',
      name: 'UrbanMobility',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=UrbanMobility',
      website: 'https://urbanmobility.io',
      slug: 'urban-mobility',
      description: 'Fleet management for shared micromobility.',
    },
    sector: { code: 'mobility', name: 'Mobility' },
    subsector: { code: 'micromobility', name: 'Micromobility' },
    stage: 'pre_seed',
    business_model: 'B2B SaaS',
    founded_year: 2023,
    employee_count: 9,
    hq_location: { city: 'Miami', state: 'FL', country: 'USA' },
    short_summary: 'Software for scooter and bike share operators.',
    pitch_summary: 'UrbanMobility provides fleet ops software for shared micromobility. Rebalancing, maintenance, compliance. 3 city pilots. Pre-revenue. Seeking pre-seed.',
    current_Readiness_score: 41,
    score_delta: 2,
    latest_metrics: {
      mrr: 5000,
      arr: 60000,
      revenue_ttm: 28000,
      gross_margin_pct: 45,
      burn_monthly: 62000,
      runway_months: 6,
      headcount: 9,
      customer_count: 3,
      cac: 25000,
      ltv: 95000,
      churn_rate_pct: 0,
      nps_score: 32,
    },
    tags: ['Mobility', 'SaaS', 'Urban'],
    founders: [
      {
        full_name: 'Jake Martinez',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JakeMartinez',
        bio: 'Ex-Lime. Operations background.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 41,
      badge: 'early',
      categories: buildCategories(41, [-6, -3, 0, -5, -8, -4, -5]),
      missing_data: [
        { item: 'Pitch deck', severity: 'high' },
        { item: 'Financial model', severity: 'high' },
      ],
    },
  },
  {
    org_id: 'startup-biogenesis',
    org: {
      id: 'startup-biogenesis',
      name: 'BioGenesis',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=BioGenesis',
      website: 'https://biogenesis.bio',
      slug: 'biogenesis',
      description: 'Synthetic biology platform for biomanufacturing.',
    },
    sector: { code: 'biotech', name: 'Biotech' },
    subsector: { code: 'synbio', name: 'Synthetic Biology' },
    stage: 'series_b',
    business_model: 'B2B Platform',
    founded_year: 2018,
    employee_count: 78,
    hq_location: { city: 'Cambridge', state: 'MA', country: 'USA' },
    short_summary: 'Platform for designing organisms for industrial production.',
    pitch_summary: 'BioGenesis accelerates biomanufacturing. Our platform designs and optimizes organisms for sustainable materials, food, and chemicals. 8 partners. $12M ARR. Breakthrough results.',
    current_Readiness_score: 88,
    score_delta: 3,
    latest_metrics: {
      mrr: 1000000,
      arr: 12000000,
      revenue_ttm: 11500000,
      gross_margin_pct: 72,
      burn_monthly: 450000,
      runway_months: 24,
      headcount: 78,
      customer_count: 8,
      cac: 180000,
      ltv: 1200000,
      churn_rate_pct: 0,
      nps_score: 65,
    },
    tags: ['Biotech', 'Sustainability', 'Platform'],
    founders: [
      {
        full_name: 'Dr. Yuki Tanaka',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YukiTanaka',
        bio: 'PhD Stanford. 20 years in synbio.',
        is_primary: true,
      },
      {
        full_name: 'Dr. Lisa Chen',
        title: 'CSO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LisaChen',
        bio: 'Ex-Ginkgo. Metabolic engineering expert.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 88,
      badge: 'exceptional',
      categories: buildCategories(88, [1, 0, 2, 0, 1, 0, 1]),
      missing_data: [],
    },
  },
  {
    org_id: 'startup-proptech',
    org: {
      id: 'startup-proptech',
      name: 'PropTech Solutions',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=PropTechSolutions',
      website: 'https://proptechsolutions.com',
      slug: 'proptech-solutions',
      description: 'Property management software for multifamily.',
    },
    sector: { code: 'real_estate', name: 'Real Estate' },
    subsector: { code: 'proptech', name: 'PropTech' },
    stage: 'seed',
    business_model: 'B2B SaaS',
    founded_year: 2021,
    employee_count: 28,
    hq_location: { city: 'Atlanta', state: 'GA', country: 'USA' },
    short_summary: 'All-in-one property management for 50+ unit buildings.',
    pitch_summary: 'PropTech Solutions replaces legacy property management tools. Leasing, maintenance, accounting in one platform. 180 properties. $920K ARR. Strong growth in Southeast.',
    current_Readiness_score: 54,
    score_delta: 1,
    latest_metrics: {
      mrr: 77000,
      arr: 924000,
      revenue_ttm: 780000,
      gross_margin_pct: 62,
      burn_monthly: 88000,
      runway_months: 10,
      headcount: 28,
      customer_count: 42,
      cac: 12000,
      ltv: 55000,
      churn_rate_pct: 5.2,
      nps_score: 38,
    },
    tags: ['Real Estate', 'SaaS', 'PropTech'],
    founders: [
      {
        full_name: 'Kevin Brown',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KevinBrown',
        bio: '20 years in property management.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 54,
      badge: 'developing',
      categories: buildCategories(54, [-3, -1, 1, -2, -2, 0, -1]),
      missing_data: [
        { item: 'Pitch deck update', severity: 'medium' },
        { item: 'Churn analysis', severity: 'high' },
      ],
    },
  },
  {
    org_id: 'startup-cybershield',
    org: {
      id: 'startup-cybershield',
      name: 'CyberShield',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=CyberShield',
      website: 'https://cybershield.security',
      slug: 'cybershield',
      description: 'Zero-trust endpoint security for remote work.',
    },
    sector: { code: 'cybersecurity', name: 'Cybersecurity' },
    subsector: { code: 'endpoint', name: 'Endpoint Security' },
    stage: 'series_a',
    business_model: 'B2B SaaS',
    founded_year: 2020,
    employee_count: 45,
    hq_location: { city: 'Denver', state: 'CO', country: 'USA' },
    short_summary: 'Zero-trust agents for distributed teams.',
    pitch_summary: 'CyberShield enforces zero-trust at the endpoint. Works with any identity provider. 85 enterprise customers. $2.1M ARR. SOC 2 certified.',
    current_Readiness_score: 73,
    score_delta: 4,
    latest_metrics: {
      mrr: 175000,
      arr: 2100000,
      revenue_ttm: 1950000,
      gross_margin_pct: 76,
      burn_monthly: 140000,
      runway_months: 18,
      headcount: 45,
      customer_count: 85,
      cac: 18000,
      ltv: 95000,
      churn_rate_pct: 2.4,
      nps_score: 52,
    },
    tags: ['Security', 'Zero Trust', 'Enterprise'],
    founders: [
      {
        full_name: 'Amanda Foster',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AmandaFoster',
        bio: 'Ex-CrowdStrike. CISO experience.',
        is_primary: true,
      },
      {
        full_name: 'Vikram Singh',
        title: 'CTO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VikramSingh',
        bio: 'Ex-Palo Alto. Security research.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 73,
      badge: 'strong',
      categories: buildCategories(73, [1, 0, 2, 0, 1, 2, 0]),
      missing_data: [{ item: 'Reference customers', severity: 'low' }],
    },
  },
  {
    org_id: 'startup-foodtech',
    org: {
      id: 'startup-foodtech',
      name: 'FoodTech Labs',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=FoodTechLabs',
      website: 'https://foodtechlabs.com',
      slug: 'foodtech-labs',
      description: 'Supply chain visibility for food manufacturers.',
    },
    sector: { code: 'foodtech', name: 'Foodtech' },
    subsector: { code: 'supply_chain', name: 'Supply Chain' },
    stage: 'seed',
    business_model: 'B2B SaaS',
    founded_year: 2022,
    employee_count: 19,
    hq_location: { city: 'Portland', state: 'OR', country: 'USA' },
    short_summary: 'Traceability and quality for food supply chains.',
    pitch_summary: 'FoodTech Labs provides end-to-end visibility for food manufacturers. Traceability, quality, compliance. 25 customers. $580K ARR. Critical for recalls and audits.',
    current_Readiness_score: 62,
    score_delta: 3,
    latest_metrics: {
      mrr: 48000,
      arr: 576000,
      revenue_ttm: 440000,
      gross_margin_pct: 68,
      burn_monthly: 72000,
      runway_months: 11,
      headcount: 19,
      customer_count: 25,
      cac: 15000,
      ltv: 78000,
      churn_rate_pct: 3.8,
      nps_score: 47,
    },
    tags: ['Food', 'Supply Chain', 'B2B'],
    founders: [
      {
        full_name: 'Maria Santos',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MariaSantos',
        bio: 'Ex-General Mills. Supply chain exec.',
        is_primary: true,
      },
    ],
    assessment: {
      overall_score: 62,
      badge: 'developing',
      categories: buildCategories(62, [0, 0, 1, -1, 0, 2, 0]),
      missing_data: [
        { item: 'Market sizing', severity: 'medium' },
        { item: 'Competitive analysis', severity: 'low' },
      ],
    },
  },
  {
    org_id: 'startup-quantumleap',
    org: {
      id: 'startup-quantumleap',
      name: 'QuantumLeap',
      org_type: 'startup',
      logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=QuantumLeap',
      website: 'https://quantumleap.tech',
      slug: 'quantum-leap',
      description: 'Quantum computing software for optimization.',
    },
    sector: { code: 'deeptech', name: 'Deeptech' },
    subsector: { code: 'quantum', name: 'Quantum Computing' },
    stage: 'series_c',
    business_model: 'B2B SaaS',
    founded_year: 2017,
    employee_count: 120,
    hq_location: { city: 'Boston', state: 'MA', country: 'USA' },
    short_summary: 'Quantum algorithms for logistics and finance.',
    pitch_summary: 'QuantumLeap develops quantum algorithms for optimization problems in logistics, finance, and drug discovery. Partnerships with IBM, Google, AWS. $15M ARR. Pre-IPO trajectory.',
    current_Readiness_score: 94,
    score_delta: 1,
    latest_metrics: {
      mrr: 1250000,
      arr: 15000000,
      revenue_ttm: 14200000,
      gross_margin_pct: 88,
      burn_monthly: 200000,
      runway_months: 48,
      headcount: 120,
      customer_count: 35,
      cac: 85000,
      ltv: 420000,
      churn_rate_pct: 0.8,
      nps_score: 76,
    },
    tags: ['Quantum', 'Deeptech', 'Enterprise'],
    founders: [
      {
        full_name: 'Dr. Alan Wright',
        title: 'CEO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlanWright',
        bio: 'MIT quantum physics. Ex-Microsoft Research.',
        is_primary: true,
      },
      {
        full_name: 'Dr. Sofia Ivanova',
        title: 'CPO',
        photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SofiaIvanova',
        bio: 'Stanford CS. Quantum algorithms expert.',
        is_primary: false,
      },
    ],
    assessment: {
      overall_score: 94,
      badge: 'exceptional',
      categories: buildCategories(94, [0, 0, 1, 0, 0, 0, 0]),
      missing_data: [],
    },
  },
];
